DATA_PATH = "./data/TCGA-PRAD/data.csv"
DESCRIPTION_PATH = "./data/TCGA-PRAD/description.csv"
INTERACTION_PATH = None 
OUTPUT_DIR_PATH = "./data/TCGA-PRAD/"

REFERENCE_GROUP = "Normal"
EXPERIMENTAL_GROUP = "Tumor"

CORRELATION = "spearman"
ALTERNATIVE = "two-sided"
PROCESS_NUMBER = 16

FDR_THRESHOLD = 0.05
